-- New EmailType values: welcome email + one per notification type mirrored to email.
-- ALTER TYPE ... ADD VALUE is non-transactional in Postgres; IF NOT EXISTS makes it
-- safe to re-run.
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'WELCOME';
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'CONTACT_MESSAGE';
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'NOTIFICATION_FORUM_THREAD';
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'NOTIFICATION_FORUM_COMMENT';
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'NOTIFICATION_ASSESSMENT_SUBMITTED';
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'NOTIFICATION_ASSESSMENT_GRADED';
