-- Course-completion + feedback email types. ALTER TYPE ... ADD VALUE is
-- non-transactional; IF NOT EXISTS makes it safe to re-run.
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'COURSE_COMPLETED';
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'FEEDBACK_REQUEST';
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'FEEDBACK_RECEIVED';
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'FEEDBACK_RECEIVED_ADMIN';
