ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REGISTRATION_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REGISTRATION_REVIEWED';

ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'NOTIFICATION_REGISTRATION_SUBMITTED';
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'NOTIFICATION_REGISTRATION_REVIEWED';
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'REGISTRATION_RECEIVED';
