-- New NotificationType values for assignment events
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ASSIGNMENT_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ASSIGNMENT_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ASSIGNMENT_GRADED';

-- Mirror EmailType values for emails sent alongside the in-app notifications
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'NOTIFICATION_ASSIGNMENT_CREATED';
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'NOTIFICATION_ASSIGNMENT_SUBMITTED';
ALTER TYPE "EmailType" ADD VALUE IF NOT EXISTS 'NOTIFICATION_ASSIGNMENT_GRADED';
